### ISSUE TITLE
Muting doesnt sync

### ISSUE THREAD

**Issue by emongev** [Frosthaven/voicemeeter-windows-volume#10]
Version v1.6.1.0
Voicemeeter Potato

Muting with my media keys isnt syncing to voicemeeter.

**Comment by Frosthaven** [comment]
I'm looking in to this now

**Comment by Frosthaven** [comment]
This should be solved as of the [latest release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.6.2.0). Let me know if this works for you!

**Comment by emongev** [comment]
That was quick really appreciate the quick fix!
