### ISSUE TITLE
the latest beta version restarting windows volume spike volume to 100%

### ISSUE THREAD

**Issue by thu2468** [Frosthaven/voicemeeter-windows-volume#12]
Volume goes up to 100% and doesnt restore

**Comment by Frosthaven** [comment]
Does this occur after a specific restart event?

I don't like that I've been coding this workaround blindly so I'm going to set up my environment to introduce this driver bug artificially on my end.

**Comment by thu2468** [comment]
![image](https://user-images.githubusercontent.com/1341488/144896536-8cca8cff-dd73-4cc8-99a9-9e8842592033.png)
So when having app launch on causes it (What i did was have voicemeeter on and then restarted your app and then volume get changed to 100%)
and then sometime i come back next day volume get set to 100% after login from sleep or something like that from lock screen

so maybe it has to do with the Restart Audio Engine on.. setting setting

**Comment by thu2468** [comment]
![image](https://user-images.githubusercontent.com/1341488/144897235-20f07d4d-586c-444f-a979-60ed36f50c4b.png)
Also when restarting audio engine in voicemeeter without the app changes voicemeeter DB to +12 for some reason

**Comment by Frosthaven** [comment]
Aha ok, so it seems like the strange audio behavior is coming from voicemeeter's side on this one then. Are you on the latest version of voicemeeter?

I may be able to work around this for audio restarts that my app initiates.

**Comment by thu2468** [comment]
Yes im on latest version on voicemeeter.

But when I close your app and then restart audio engine on voicemeeter the dB doesn't spike to +12
