### ISSUE TITLE
Revert to the "initial_volume" when pressing on the "Restart Audio Engine" setting in VoiceMeeter.

### ISSUE THREAD

**Issue by ahs16** [Frosthaven/voicemeeter-windows-volume#2]
Hey @Frosthaven , when I press on the **Restart Audio Engine** setting in VoiceMeeter the volume becomes 100% automatically instead of reverting to the **initial_volume**.

Sincerely, ahs16

**Comment by Frosthaven** [comment]
@ahs16 thanks for the feedback! Feel free to join us over on this issue ticket: https://github.com/Frosthaven/voicemeeter-windows-volume/issues/1

closing this one as duplicate
