### ISSUE TITLE
Preserve/Restore mute setting

### ISSUE THREAD

**Issue by EagleDev91** [Frosthaven/voicemeeter-windows-volume#20]
Hi,

Currently, on muting, all bind outputs will be muted. And even on unmute, all outputs will be unmuted, even if one was muted before.

Example:
Before mute-press:
  Speakers -> muted
  Headphones -> unmuted

After mute-press:
  Speakers -> muted
  Headphones -> muted

After unmuting again:
<table>
<tr>
<th> Currently; </th>
<th> Expecting:</th>
</tr>
<tr>
<td>
  Speakers -> unmuted<br>
  Headphones -> unmuted
</td>
<td>
  Speakers -> muted<br>
   Headphones -> unmuted 
</td>
</tr>
</table>

It would be great if the current mute state of each binding could be preserved so on unmute it will restore the original state. It's sometimes really annoying if suddenly all outputs will play the sound simultaneous and you have to mute specific outputs manually again.

Hope you agree and implement that :)

**Comment by Frosthaven** [comment]
Hey thanks so much for the suggestion! I can see where we might want the mute state to be more than a device agnostic toggle.

In your recommendation, you see unmuting as returning to the previous state. I can see how that might work!

For your use case, would it be better to simply restore the pre-mute state, or to let you decide explicitly which channels the mute button impacts?

**Comment by EagleDev91** [comment]
Glad to hear that!

Restoring the previous state (of all bonded outputs) is the most practicable, I think.
