### ISSUE TITLE
Volume not scaling correct from system with voicemeeter

### ISSUE THREAD

**Issue by thu2468** [Frosthaven/voicemeeter-windows-volume#21]
When system volume is at 22 Voice meter is at -1.2 DB

**Comment by metahexane** [comment]
Hi @thu2468 , thanks for chiming in and using the repo! This is actually intended behavior, as dB scales logarithmically with respect to windows volume sliders. This is better described in #16 .

**Comment by Frosthaven** [comment]
Linear volume scaling is now an option available in the latest release https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.4.0
