### ISSUE TITLE
Also found a bug that i need to reapply cracking fix.

### ISSUE THREAD

**Issue by thu2468** [Frosthaven/voicemeeter-windows-volume#22]
Whenever i come back from standby or something i need to reapply cracking fix. my friend would hear my mic cracking

**Comment by Frosthaven** [comment]
Cracklefix will now automatically re-apply if checked after system resume events as of the latest release https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.4.0
