### ISSUE TITLE
Linear Volume Change

### ISSUE THREAD

**Issue by blacktornadog7** [Frosthaven/voicemeeter-windows-volume#24]
It would be nice to have a "Linear Volume Change" i.e if Windows have a volume scale from 0-100 and VoiceMeeter has -60db to 12db a 1:1 scale would be 1:0.72db (and for when Max Gain Limit is set to 0db it would be 1:0.60db).

Like that there would be much more granual control over the volume, in the current scale a 30 volume in Windows is 1.5db in VoiceMeeter which honestly I felt is too much harch of a jump.

Also great work on this app, I started looking for this exact thing right after I installed VoiceMeeter, I really wonder why VoiceMeeter doesn't have this app features built-in in the first place, it's really a must have!

**Comment by Jerrk** [comment]
this was discussed a while back in #16 

i'm currently using [v1.7.2.0](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.2.0) which doesn't have the auto-start fix, but i much prefer the older volume scale.

**Comment by metahexane** [comment]
Hi everyone! Voicemeeter has built in linear scaling through volume keys (not sure if this repo is used by you guys for that purpose, but I use it for my volume buttons, since it's the only way I change my volume). It can be found in Menu > Shortcut Key (Hook) > Hook Volume Keys. If you do not like the increments, you could always use macro buttons to set your own increments to hook up with volume up/down keys.

**Comment by blacktornadog7** [comment]
Hi @metahexane, yeah I know there's an option to hook the vol+/vol- keys to voicemeeter, and also with voicemeeter macro buttons.

But the problem is that there is no osd/hud when adjusting the volume, and it works independently of Windows volume which means you always have to use the keys, which means you can't adjust the volume from the icon tray just with a mouse, and honestly it's a kind of an inconvenience since I'm so used to that, and especially when using [EarTrumpet](https://github.com/File-New-Project/EarTrumpet) 
(which lets you adjust the volume with the mouse wheel just by hovering on the sound icon tray and muting by clicking the mouse wheel)
Though there is [this osd/hud app](https://github.com/A-tG/VoicemeeterFancyOSD/releases), but it still have the same above issues.

So yeah... because all that I rarely ever used Voicemeeter after just installing recenlty.
Habits are hard to break 😂

**Comment by Frosthaven** [comment]
Linear volume scaling is now an option with the latest release https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.4.0
