### ISSUE TITLE
Hey...

### ISSUE THREAD

**Issue by TheJAXi** [Frosthaven/voicemeeter-windows-volume#29]
Not sure if this is the right way to ask for this, but would it be possible for you to make "a copy" of this app, but in a different way. I've been long searching for an app that would do the exact thing yours does, but there's just one problem. I have two output sources that I need to change the volume of daily (dozen times). VAIO & AUX. Would it be possible to link somehow keys like with macro buttons (currently having volume keys on VAIO and shift+volume keys on AUX) to the two devices? Or at least have some kind of overlay/display sorta thing to see visually the levels... Been hoping for this from the actual devs for years. 

= would be happy if you'd make some kinda freaky app that hooks two windows sound devices somehow & displays two different volume overlays (like not at the same time). The app called "Modern Flyouts" is kinda sick, I was hoping it could some how link to voicemeeter but that isn't possible. Is there any chance you'd be interested/capable of making such thing? Modern Flyouts v2 for voicemeeter only xx It'd be sick. A ton of help during the day as nowadays I can't afford the screen space for the whole voicemeeter app (even with 6 monitors) (and it doens't still allow changing the size of the app even).

Yeah... Probably wrong way of asking this but kinda desperate. I think other people would also find such app/tool helpful. I'm willing to pay some for it if it's necessary.

**Comment by TheJAXi** [comment]
https://github.com/A-tG/VoicemeeterFancyOSD/

Like this, but prettier xx And I'd need it to be light-weight & "safe" with all kinda software (anti-cheats & such). Modern Flyouts works perfectly (as it's the same as Windows volume pop up thing, but prettier).

Would it be possible to rework that to prettier & (possibly more rock solid version)?

Anyways... Goodnight to y xx

**Comment by Frosthaven** [comment]
Unfortunately this sounds outside of the scope of what I'm looking to accomplish for the project.
