### ISSUE TITLE
When Computer restart Volume spike to 100%

### ISSUE THREAD

**Issue by thu2468** [Frosthaven/voicemeeter-windows-volume#3]
I have Prevent 100% volume spike enable.

What u can do without restarting computer is
Close both program
Start Voicemeeter Window Volume
Then Run Voicemeeter Potato
and then when VM start DB shoot up to 12DB on two of my binds
i have binds on Strip 6 and 7

**Comment by thu2468** [comment]
But if i leave VM Window Volume Program on and then restart VM Potato this doesnt happen.
My Default Playback Device is VM Vaio

**Comment by Frosthaven** [comment]
Try adding "initial_volume" to your settings.json and setting it from 0-100. That should set your system volume on launch.

Eventually I plan to have this built into the menu!

**Comment by Frosthaven** [comment]
@thu2468 I've uploaded a new version that may asssist over on the [releases](https://github.com/Frosthaven/voicemeeter-windows-volume/releases) page. Let me know if the "Restore Windows Volume" feature does what you need.

**Comment by thu2468** [comment]
Ok that works. only thing i noticed was a bit weird when using volume key was it Window device volume is 100% while DB doesnt spike. So it takes a few clicks untill windows go back down. Sorry if i didnt explain well

**Comment by thu2468** [comment]
that only happen when ur trying to lower the volume

**Comment by Frosthaven** [comment]
I'm having trouble reproducing this. Can you help me with this?

I'm wondering if this delay is only when you first open the programs? If you wait a moment, does everything work ok?

This app will wait for Voicemeeter to be ready, which should only take a few seconds.

Thanks!

**Comment by thu2468** [comment]
Oh so after launching both app. I click on the window volume in taskbar, show 100% and then wait a few seconds it readjust to the volume setting it had before.

**Comment by Frosthaven** [comment]
Oh okay yes that sounds right. VMWV waits for voicemeeter to settle before initiating. That'll cause a minor delay on load but then it should be good while running :)
