### ISSUE TITLE
Autostart dont work

### ISSUE THREAD

**Issue by DoodleCup** [Frosthaven/voicemeeter-windows-volume#30]
I checked the Automatically start with windows in menu. But it dont start automatically. (Windows 11 Pro).

**Comment by bgn-dev** [comment]
Since this problem is still there, i'll post a workaround. Press the windows key + r and type shell:startup. Then just put a link for the app-launcher.

**Comment by Frosthaven** [comment]
I know this has been a long-standing report that began after a few windows 11 updates for task scheduler tasks. I'll see if I can get this corrected soon:tm:

Always happy to review pull requests as well :)

**Comment by ebug64** [comment]
Thank you so much for looking into this! I noticed that it sometimes auto starts and sometimes doesn’t. Another weird thing is it doesn’t show up in the Task Manager Startup Apps for me. I don’t remember if this was normal or not though as most of the time in the past clicking the option in the menu usually worked fine.

**Comment by Boerny41** [comment]
Also applies to #31 

Until it's implemented, you can do a simple workaround using the Task Scheduler.

First create a batch that runs the app-launcher.vbs, then create a scheduled task that runs the batch with high privileges when you log in (it can't run .vbs files).
Below are two links that explain in detail how to do these two steps.


https://stackoverflow.com/questions/29663480/windows-task-scheduler-doesnt-run-vbscript
https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts/

**Comment by Frosthaven** [comment]
release [1.8.0.1](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.8.0.1) may solve this issue. Feel free to give it a run and let me know :)

**Comment by Frosthaven** [comment]
The [latest release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/) should put this to rest

let me know!

**Comment by omexlu** [comment]
@Frosthaven For me it still doesnt work, it doesnt start with windows and also there is no scheudule create, fpr me its no problem i will start it after booting pc :)
