### ISSUE TITLE
Ability to edit max gain limiter

### ISSUE THREAD

**Issue by niaz-ahamed77** [Frosthaven/voicemeeter-windows-volume#37]
Hi! I just discovered this app and it's simply amazing! For the past year+, I've been using macro buttons but I'm excited to finally be able to see a visual volume slider again :)

I was trying to customize it so that it suits my needs and was wondering about how to set my gain levels between -50 to +5. I noticed that it jumps to -60 when the volume gets low enough, which is great, but I don't have the ability to adjust the max to +5. If I disable the  "Limit max gain to 0db" function, it seems to set +12 as the max gain (voicemeeter default I think).

It would be fantastic to be able to customize the max so that it suits our audio setup.

Thanks again for this app!

**Comment by IWW-Shane** [comment]
Hey thanks for the reply!

We do have some settings you can play with that aren't shown in the UI - these are located in the `INSTALL_DIRECTORY/required/settings.json` file.

You'll be looking to specifically change these two values and then restart VMWV:

```json
{
  "gain_min": -60,
  "gain_max": 12,
}
```

**Comment by Frosthaven** [comment]
Hey thanks for the reply!

We do have some settings you can play with that aren't shown in the UI - these are located in the `INSTALL_DIRECTORY/required/settings.json` file.

You'll be looking to specifically change these two values and then restart VMWV:

```json
{
  "gain_min": -60,
  "gain_max": 12,
}
```
