### ISSUE TITLE
Voicemeeter crackle when PC auto turn off display. 

### ISSUE THREAD

**Issue by thu2468** [Frosthaven/voicemeeter-windows-volume#4]
I have the Apply crackling fix enable.
turn off display is set to 10min.

**Comment by Frosthaven** [comment]
Can you open task manager and tell me what priority audiodg.exe is running at when the crackle returns?

**Comment by thu2468** [comment]
cpu affinity is set to cpu 1

**Comment by thu2468** [comment]
also waking up from sleep also does the same thing

**Comment by thu2468** [comment]
Maybe a auto restart Voicemeeter when waking up from Sleep/Hibernating/Display turning back on will help

**Comment by Frosthaven** [comment]
> Maybe a auto restart Voicemeeter when waking up from Sleep/Hibernating/Display turning back on will help

If you can confirm that restarting voicemeeter solves this issue, I will keep the ticket open for potential future enhancements.

**Comment by thu2468** [comment]
yes restarting Voicemeeter fix the crackling issue

**Comment by Jerrk** [comment]
i can also confirm that i occasionally have this issue with voicemeeter - long before installing VWV.
"restart audio engine" always fixes the issue so it would indeed seem to be an issue endemic to voicemeeter itself.

you could perhaps run a macro that detects when your computer wakes from sleep or when your displays turn on.
though i'm not sure what program would do that for you, maybe displayfusion (i know it has a trigger for "system wakes from sleep" and "desktop unlocked").

**Comment by Frosthaven** [comment]
That definitely sounds doable. A sort of extension to voicemeeter's automatic engine restarts.

The road to there seems to be:

- Extend API coverage to be able to transmit a request engine restarts (currently supported in the official API, but not currently implemented)
 through voicemeeter
- Detect the events: resume from standby, display change, potentially audio adapter changes
- react to events if driver workaround is enabled

Sounds like we have a roadmap for this enhancement!

**Comment by Frosthaven** [comment]
Update: The primary obstacle was expanding the support of an upstream dependency to support sending one-off commands. I've forked the dependency and enhanced it as of https://github.com/Frosthaven/voicemeeter-connector/commit/bce957613275e020ba4fa36ba6a6e89d2b263038.

I have some ideas on how best to tackle firing an event on "wakeup", so with the upstream changes done it should not be too long now.

Question: Does changing displays actually cause this issue as well? Or is it *just* waking from standby?

**Comment by thu2468** [comment]
It  happens  when either on sleep/hibernating or when display turn off
![image](https://user-images.githubusercontent.com/1341488/140850265-381be9d6-9939-4935-9e15-20d0c6dd4ba4.png)
These two options

**Comment by Frosthaven** [comment]
I've uploaded a pre-release that has the ability to auto-restart the engine on device changes. It doesn't specifically target sleep/wake, but I'd be curious if it still triggers from the audio device change portion. If not, let me know and I'll make sleep/standby resume the next thing on the list.

**Comment by Jerrk** [comment]
> 
> 
> I've [uploaded a pre-release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.6.1) that has the ability to auto-restart the engine on device changes. It doesn't specifically target sleep/wake, but I'd be curious if it still triggers from the audio device change portion. If not, let me know and I'll make sleep/standby resume the next thing on the list.

under windows playback devices if i choose a new default playback device it takes around 20 seconds until the audio engine restarts (and sometimes it doesn't restart at all), and then when the engine restarts the volume spikes to 100%.

is this option supposed to work on default audio device change or is it supposed to be on a new audio device connected?

**Comment by Frosthaven** [comment]
> is this option supposed to work on default audio device change or is it supposed to be on a new audio device connected?

it should be referencing the same list you get by running `get-wmiobject win32_sounddevice` in powershell. it wont show if you plug in a 3.5mm jack, as an example (since the soundcard is always "plugged in") but it should trigger on device availability changes (plugged in and removed).

**Comment by Jerrk** [comment]
> 
> 
> > is this option supposed to work on default audio device change or is it supposed to be on a new audio device connected?
> 
> it should be referencing the same list you get by running `get-wmiobject win32_sounddevice` in powershell. it wont show if you plug in a 3.5mm jack, as an example (since the soundcard is always "plugged in") but it should trigger on device availability changes (plugged in and removed). But I still have some expanding on it to do yet.
> 
> hows the volume syncing?

volume syncing has been working for a couple versions iirc when switching default playback device like normal.

if i enable the option "restart audio engine on audio device change" the audio engine will restart randomly (in my situation atleast). and then it will spike the volume to 100% even with the "prevent 100% volume spikes" turned on.

if i restart audio engine normally it does NOT spike to 100% volume.

**Comment by Frosthaven** [comment]
I've got a pre-release on the burner [over here](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.0).

This adds the ability to automatically restart the audio engine when returning from sleep/hibernate/standby.

**In the case that it doesn't solve this ticket:**

There is no way (that I'm aware of) to track when a monitor specifically is put to sleep by the system.

More research would need to be done into exactly what about the monitor going to sleep causes the need for an engine restart, and likely would need to be fixed in Voicemeeter itself.

**Comment by thu2468** [comment]
![image](https://user-images.githubusercontent.com/1341488/143726101-76982c6b-c1a7-4573-b1d7-521e7760c466.png)
no way to detect this?

**Comment by thu2468** [comment]
it is under 
Control Panel\Hardware and Sound\Power Options\Edit Plan Settings

**Comment by Frosthaven** [comment]
Not directly, no. What I can *probably do* is read that setting and then compare it to the machine's recorded idle time to approximate the event myself. It's a bit messier but it may just work. Stay tuned.

**Comment by Frosthaven** [comment]
Ok I have a loose method of detecting monitor wake worth testing [in this pre-release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.7.1.0).

Let me know!
