### ISSUE TITLE
Audio semi-randomly cuts out briefly

### ISSUE THREAD

**Issue by genderneutralnoun** [Frosthaven/voicemeeter-windows-volume#42]
Just want to say first off that I really appreciate this project, it changed voicemeeter from "almost perfect" to "essentially perfect" for me.
The bug: Sometimes, generally when my computer is running demanding tasks like 3D video games, the audio will cut out briefly, come back on, cut again, and then come back on again. I wasn't able to determine any other pattern to it other than that it seems to happen mostly when doing demanding tasks. I asked on the VM discord for help with the issue, and when I said I was using this extension, the person helping me said to try with your extension disabled, and so far, it seems like the problem isn't happening anymore since I've stopped using your extension. Since it happens randomly, it's hard to tell for certain.
I will be happy to provide any information you need to help determine the cause of this bug.

**Comment by BoogieHasFun** [comment]
happens with me too, and i really need this to have voicemeeter be good

**Comment by Frosthaven** [comment]
Hey gang, thought I might throw some context in here - the brief cut-ins and cut-outs would be from the "automatically restart audio engine on..." options. If for some reason your system has a device that is connecting or disconnecting behind the scenes, it'll trigger audio engine restarts when those options are enabled. I ran into this with my spare laptop with a device that would do this periodically (a class of misbehavior, if you ask me).

The latest version has a way of blacklisting devices that are doing this, but I haven't super documented it. I might recommend either disabling your automatic audio engine restarts or leveraging the debug launcher to see what device is connecting/disconnecting and then adding that  to the blacklist in settings json (while using restart on all device changes, not audio only). It should be enough to work around the issue.

Hope this information helps!

**Comment by BoogieHasFun** [comment]
> Hey gang, thought I might throw some context in here - the brief cut-ins and cut-outs would be from the "automatically restart audio engine on..." options. If for some reason your system has a device that is connecting or disconnecting behind the scenes, it'll trigger audio engine restarts when those options are enabled. I ran into this with my spare laptop with a device that would do this periodically (a class of misbehavior, if you ask me).
> 
> The latest version has a way of blacklisting devices that are doing this, but I haven't super documented it. I might recommend either disabling your automatic audio engine restarts or leveraging the debug launcher to see what device is connecting/disconnecting and then adding that to the blacklist in settings json (while using restart on all device changes, not audio only). It should be enough to work around the issue.
> 
> Hope this information helps!


thanks man, i will try turning off auto audio engine restarts and see if it works!

**Comment by BoogieHasFun** [comment]
i haven't had this issue after turning that off for 4 hours.

after 7 hours it randomly did it again, but it is doing it less

**Comment by Frosthaven** [comment]
> i haven't had this issue after turning that off for 4 hours.
after 7 hours it randomly did it again, but it is doing it less

This is great to hear! Anytime that happens outside of the options in VMWV, it is likely that your voicemeeter itself restart the engine. Do you have Voicemeeter's auto-restart on A1 device change enabled?

**Comment by BoogieHasFun** [comment]
nope

**Comment by genderneutralnoun** [comment]
I meant to say this ages ago, but turning off auto-restart completely fixed it for me, for the record.

**Comment by BoogieHasFun** [comment]
i haven't had the issue at all anymore. it's safe to close this now.

**Comment by Frosthaven** [comment]
Really happy to hear this has been resolved - thanks for being a part of the discussion, honestly. You'll never know how much I appreciate it!
