### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by TheBoogle** [Frosthaven/voicemeeter-windows-volume#6]
**Ran the program for around 8 hours and at the end of the day was using around this much memory.**

![image](https://user-images.githubusercontent.com/33293053/141670567-39846397-e437-412b-a75e-94959fadb513.png)

**How much it uses when I first run it.**
 
![image](https://user-images.githubusercontent.com/33293053/141670668-4ee5c4e9-244b-400a-a87b-10edb4ef5423.png)

**Specs**

![image](https://user-images.githubusercontent.com/33293053/141670606-2042f055-ce91-4d10-8a06-c79f7b9a1bca.png)
![image](https://user-images.githubusercontent.com/33293053/141670604-a6545c48-7f3c-4e86-812d-331da89bcdbe.png)

**Comment by Frosthaven** [comment]
Yep this has been addressed in the latest [pre-release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.6.1)

Long story short a required dependency was flooding the memory with events. I've rebuilt my own scanning into this app to no longer rely on the offending package.

I'll be taking the linked release out of pre-release status this week if all goes well.

**Comment by TheBoogle** [comment]
Thanks for the quick response! Using less memory already, very awesome, thank you.

**Comment by Frosthaven** [comment]
Closed as of [v1.6.1.0 release](https://github.com/Frosthaven/voicemeeter-windows-volume/releases/tag/v1.6.1.0)

Thanks again for the support!
